spring:
  application:
    name: hvordan-gikk-quizen-backend

server:
  address: 0.0.0.0
  port: ${PORT:8080}
  forward-headers-strategy: framework

cors:
  allowed-origin: https://hvordangikkquizen.no
