spring:
  config:
    import: optional:file:.env.local[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

server:
  port: 8080

cors:
  allowed-origin: http://localhost:5173
