spring:
  config:
    import: optional:file:environments/.env.prod[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://hvordan-gikk-quizen-backend.fly.dev/login/oauth2/code/google"

server:
  address: 127.0.0.1
  port: ${PORT:8080}
  forward-headers-strategy: framework

cors:
  allowed-origin: https://hvordangikkquizen.no
